Added deployment annotations to chart
mastodon/chart pull request #64
Opened 2023-04-19 22:33 UTC by timetinytim

Added the ability to define custom annotations for deployment objects.

2023-04-20 09:15 UTC, renchap requested changes
You may want to allow deployment-specific annotations as well, as we currently do for pod annotations (so its consistent).

For example for web:

```
{{- with (default .Values.deploymentAnnotations .Values.mastodon.web.deploymentAnnotations) }}
```

2023-04-20 15:16 UTC, timetinytim commented on values.yaml
> +deployAnnotations: {}
Ah both are good calls. Updated!

2023-04-21 16:13 UTC, timetinytim commented
@renchap Apologies for bothering, but if everything looks good now, I'd like to get this merged so I can ensure everything stays up to date

2023-04-21 16:16 UTC, renchap approved these changes
Looks good! 👍

2023-04-21 16:16 UTC, merged