Allow dual-stack operation on clusters so equipped.
mastodon/chart pull request #68
Opened 2023-06-11 18:20 UTC by cerebrate

At the moment, the Helm chart does not allow clean installation on Kubernetes clusters running in dual-stack mode.

For example, on my own k3s cluster, the Mastodon services are assigned only IPv6 addresses and use only IPv6 endpoints, which fails both IPv4 clients and causes problems with the Mastodon pods which, at the moment, only bind to IPv4 addresses on a dual-stack cluster. (The related issue to fix that problem is here: https://github.com/mastodon/mastodon/issues/25371 ; at the moment I had to bypass it by hacking BIND definitions into this Helm chart, but a proper fix would obviously be preferable.)

This PR remedies the problem by setting _ipFamilyPolicy: PreferDualStack_ on the services the chart creates, which makes dual-stack clusters operate correctly and should have no side-effects on single-stack clusters.

2023-06-11 19:47 UTC, SISheogorath requested changes
This will break existing deployments, since the `ipFamilyPolicy` field is immutable.

https://kubernetes.io/docs/concepts/services-networking/dual-stack/#services

2023-06-11 22:05 UTC, cerebrate commented
That's true.

I'm not certain what the best approach is. On the one hand, I'm not necessarily against making _ipFamilyPolicy_ a configurable option in the chart, but I would still prefer the default to be _PreferDualStack_, since otherwise it's just Another Damn Thing to do for every future installation. Admittedly, this requires present installations upgrading to manually change it to _SingleStack_ to avoid breakage, but in the big picture, there are less of them than all future and fixed deployments.

On the other hand, if they have to do that _anyway_, the best option might be the same as the one noted for mastodon/mastodon#19706 in the README.md and simply instruct people to delete the two services before they `helm upgrade`, something which would only have to be done once per installation.

Thoughts?

2025-02-10 10:45 UTC, timetinytim commented
Finally getting around to this~

This is a good change, but yes, it will break existing deployments. However, I am currently getting several PRs ready in preparation for bumping the chart up to App version 4.3, which will be a major (i.e. breaking) version bump, so I think the best thing to do is merge this as everything else is getting merged, and add notes in the changelog of how to deal with this.

2025-03-06 09:00 UTC, timetinytim approved these changes
Getting ready to merge this now, before the bump to chart version v6. I will included a note in the changelog about this breaking change, and how to deal with it.

2025-03-06 09:42 UTC, merged